import type { Metadata } from "next";
import "./globals.css";
import { Barlow_Semi_Condensed, Roboto_Slab } from 'next/font/google'

const barlowSemiCondensed = Barlow_Semi_Condensed({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-barlow-semi-condensed',
});
const robotoSlab = Roboto_Slab({
  weight: ['400', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto-slab',
});

export const metadata: Metadata = {
  title: "Mikael Barbeiro - O melhor corte de Patos-PB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${barlowSemiCondensed.variable} ${robotoSlab.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
